# Generated by Django 5.2.17 on 2026-09-24 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_radio_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('occupancy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='agenda.occupancy')),
            ],
        ),
    ]
